### ISSUE TITLE
Parameterized version of check_wp_update

### ISSUE THREAD

**Issue by MegaphoneJon** [jinjie/Nagios-WordPress-Update#11]
Hi there,

I forked this script to make a version that accepts the various parts of the WordPress URL separately with arguments.

I'm not sure how useful this is to you - you'd have to modify your CheckCommand and service definitions to take advantage - and I think it's only helpful if you're using Icinga2.  However, the advantage if you ARE using Icinga2 is that you can add: `vars.cms = "wordpress"` and Icinga will add the check based on existing data in the host definition.

Anyway - check it out - if it's not helpful to you, no worries!  If it is, let me know and I'll do a PR.

**Comment by PalanteJon** [comment]
Oh, oops: https://github.com/JMAConsulting/Nagios-WordPress-Update

**Comment by jinjie** [comment]
Can see you greatly improved the check script. However, your readme file is mainly based on Icinga2? I have no experience on that. So maybe you can break up the readme into Nagios and Icinga configurations? Looks like you removed the nagios configuration part.

Maybe you can put it back in and do a PR?

**Comment by PalanteJon** [comment]
Sure, I'll try and get to that tomorrow!  Just wanted to make sure you wanted this code back in upstream, since the parameterized path isn't really valuable to everyone.  I'll do as you suggest.
