### ISSUE TITLE
WordPress - 

### ISSUE THREAD

**Issue by SergiuCip** [jinjie/Nagios-WordPress-Update#3]
Hi,

I have copied the wp-version.php to the root directory where the WordPress installation is and the main plugin to my Nagios plugins directory. 

When I am running the plugin from the Nagios server I am getting this:

 WORDPRESS  -

Do you have an idea why this might be?

Thank you,

Kind regards,
Sergiu

**Comment by jinjie** [comment]
What is the URL that that you have installed the WordPress?

**Comment by SergiuCip** [comment]
Hi,

The url I have installed Wordpress is http://hyperneph.com

**Comment by SergiuCip** [comment]
Hi,

Now I am getting: WORDPRESS No input file specified. - No input file specified.

The command I am running is: /usr/lib/nagios/plugins/check_wp_update example.com/wp-version.php

**Comment by SergiuCip** [comment]
Hi, 

I have finally fixed... it was just a matter of permissions and naming.

Thank you,

Regards,
Sergiu
